- hosts: localhost
  become: yes
  tasks:
    - name: Copy WAR to Tomcat
      copy:
        src: Amazon-Web/target/Amazon.war
        dest: /home/sunil/batch11/ansible/sonar/sonar_tomcat/webapps
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
